"""005_add_hint_count_to_conversations

Revision ID: 660d57498ae1
Revises: fd7b055bf5de
Create Date: 2026-03-08 20:33:54.431776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '660d57498ae1'
down_revision: Union[str, Sequence[str], None] = 'fd7b055bf5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 rows에 기본값 0을 설정한 뒤 NOT NULL 컬럼으로 추가
    op.add_column('conversations', sa.Column('hint_count', sa.Integer(), nullable=True, server_default='0'))
    op.execute("UPDATE conversations SET hint_count = 0 WHERE hint_count IS NULL")
    op.alter_column('conversations', 'hint_count', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'hint_count')
    # ### end Alembic commands ###
