"""002_create_personas_scenarios

Revision ID: e904b6bf8787
Revises: fd30ffe919ae
Create Date: 2026-03-08 16:25:23.527828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e904b6bf8787'
down_revision: Union[str, Sequence[str], None] = 'fd30ffe919ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('personality_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('fallback_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('job', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('speech_style', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('icon_emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('intro_line', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('situation', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('goal', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('icon_emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('background_color', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_persona_id'), 'scenarios', ['persona_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_persona_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('personas')
    # ### end Alembic commands ###
