"""004_create_learning_analytics

Revision ID: fd7b055bf5de
Revises: 1cff9ba9bfd1
Create Date: 2026-03-08 20:26:56.750370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd7b055bf5de'
down_revision: Union[str, Sequence[str], None] = '1cff9ba9bfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_expressions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fluency_score', sa.Integer(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_analytics_conversation_id'), 'learning_analytics', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_learning_analytics_user_id'), 'learning_analytics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_analytics_user_id'), table_name='learning_analytics')
    op.drop_index(op.f('ix_learning_analytics_conversation_id'), table_name='learning_analytics')
    op.drop_table('learning_analytics')
    # ### end Alembic commands ###
